### ISSUE TITLE
Add new popup in version with ads

### ISSUE THREAD

**Issue by Oleg-designer** [QuasarApp/Hanoi-Towers#111]
Popup in free version must contain new text "If you want to immediately unlock all levels and also get rid of annoying ads especially for you, we have a premium version of the Towers of Hanoi". Brunch from dev, merge pull recuest in dev, after that create 2 version builds (with ads and premium), if all was good merge pull request from dev to premium and main.

**Comment by EndrII** [comment]
@IgorekLoschinin move to centre a header of enum.
From 

![изображение](https://user-images.githubusercontent.com/12465465/126440173-87e3c03d-5c65-4975-af70-02057cf72cd1.png)

To

![изображение](https://user-images.githubusercontent.com/12465465/126440432-57378f7d-5310-4a63-984e-b66694f84bee.png)

**Comment by EndrII** [comment]
@IgorekLoschinin 
And please, add more free space between items 
change a spacing property to 10 or maybe 15 points.
