### ISSUE TITLE
prepare changelog for 1.6.0.2

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/Hanoi-Towers#86]
- [x] prepare change log for repository documentations
- [x] prepare change log for play market
```
<en-US>
Введите примечания к выпуску на этом языке: en-US
</en-US>
<ja-JP>
Введите примечания к выпуску на этом языке: ja-JP
</ja-JP>
<ru-RU>
Введите примечания к выпуску на этом языке: ru-RU
</ru-RU>
<tr-TR>
Введите примечания к выпуску на этом языке: tr-TR
</tr-TR>
<uk>
Введите примечания к выпуску на этом языке: uk
</uk>
```

**Comment by Oleg-designer** [comment]
<en-US>
- Fixed performance in main menu.
- Fixed performance between switching levels.
- Fixed 0 level bug.
- Translations update.
</en-US>
<ja-JP>
- メインメニューのパフォーマンスを修正しました。
- スイッチングレベル間のパフォーマンスを修正しました。
- 0レベルのバグを修正しました。
- 翻訳が更新されました。
</ja-JP>
<ru-RU>
- Исправление производительности в главном меню.
- Исправление ​​производительности при переходе между уровнями.
- Исправлена ​​ошибка 0 уровня.
- Обновление переводов.
</ru-RU>
<tr-TR>
- Ana menüde sabit performans.
- Geçiş seviyeleri arasındaki performans düzeltildi.
- 0 seviye hatası düzeltildi.
- Çeviriler güncellemesi.
</tr-TR>
<uk>
- Виправлення продуктивності в головному меню.
- Виправлення продуктивності при переході між рівнями.
- Виправлена ​​помилка 0 рівня.
- Оновлення перекладів.
</uk>
